/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alchermd
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
        initProducts();
    }
    
    ArrayList<Product> products = new ArrayList<>();
    ArrayList<Product> selectedItems = new ArrayList<>();
    DefaultListModel<String> selectedItemsName = new DefaultListModel<>();
    
    /**
     * Initialize the items list.
     */
    private void initProducts() {
        products.add(new Product("Org Shirt",     299.95, tshirtItem));
        products.add(new Product("ID Lace",        65.00, idLaceItem));
        products.add(new Product("S.E.F Form",     50.00, sefFormItem));
        products.add(new Product("Exam Booklet",   05.00, examBookletItem));
        products.add(new Product("Athlethic Fee", 150.75, athlethicFeeItem));
        products.add(new Product("Insurance",     100.00, insuranceItem));
        products.add(new Product("Burger",         30.00, burgerItem));
        products.add(new Product("Unli Rice",      55.55, unliRiceItem));
    }
    
    /**
     * Uncheck all the product checkboxes.
     */
    private void uncheckAll() {
        for (Product product: products) {
            product.getCheckbox().setSelected(false);
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tshirtItem = new javax.swing.JCheckBox();
        insuranceItem = new javax.swing.JCheckBox();
        sefFormItem = new javax.swing.JCheckBox();
        examBookletItem = new javax.swing.JCheckBox();
        burgerItem = new javax.swing.JCheckBox();
        unliRiceItem = new javax.swing.JCheckBox();
        athlethicFeeItem = new javax.swing.JCheckBox();
        idLaceItem = new javax.swing.JCheckBox();
        addToCartButton = new javax.swing.JButton();
        uncheckAllButton = new javax.swing.JButton();
        removeItemButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartList = new javax.swing.JList<>();
        clearCartButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AMA Apalit Shopping Cart");

        tshirtItem.setText("299.95 -> Org Shirt");

        insuranceItem.setText("100.00 -> Insurance");

        sefFormItem.setText(" 50.00 -> S.E.F Form");

        examBookletItem.setText(" 05.00 -> Exam Booklet");

        burgerItem.setText(" 30.00 -> Burger");

        unliRiceItem.setText(" 55.55 -> Unli Rice");

        athlethicFeeItem.setText("150.75 -> Athlethic Fee");

        idLaceItem.setText(" 65.00 -> ID Lace");

        addToCartButton.setText("ADD TO CART");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        uncheckAllButton.setText("UNCHECK ALL");
        uncheckAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uncheckAllButtonActionPerformed(evt);
            }
        });

        removeItemButton.setText("REMOVE ITEM");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(cartList);

        clearCartButton.setText("CLEAR CART");
        clearCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartButtonActionPerformed(evt);
            }
        });

        checkoutButton.setText("CHECKOUT");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(tshirtItem)
                        .addComponent(sefFormItem)
                        .addComponent(examBookletItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(idLaceItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerItem)
                    .addComponent(athlethicFeeItem)
                    .addComponent(unliRiceItem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(removeItemButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearCartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uncheckAllButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(addToCartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(insuranceItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tshirtItem)
                    .addComponent(athlethicFeeItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceItem)
                    .addComponent(idLaceItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sefFormItem)
                    .addComponent(burgerItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unliRiceItem)
                    .addComponent(examBookletItem))
                .addGap(12, 12, 12)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addToCartButton)
                        .addGap(12, 12, 12)
                        .addComponent(uncheckAllButton)
                        .addGap(60, 60, 60)
                        .addComponent(clearCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeItemButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Add to cart action.
     * @param evt 
     */
    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        boolean anItemIsSelected = false;
        
        for (Product product: products) {
            if (product.getCheckbox().isSelected()) {
                selectedItemsName.addElement(product.getName());
                anItemIsSelected = true;
            }
        }
        
        if (!anItemIsSelected) {
            JOptionPane.showMessageDialog(this, "No products selected");
        } 
        
        uncheckAll();
        cartList.setModel(selectedItemsName);
    }//GEN-LAST:event_addToCartButtonActionPerformed

    /**
     * Uncheck all items.
     * 
     * @param evt 
     */
    private void uncheckAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uncheckAllButtonActionPerformed
        uncheckAll();
    }//GEN-LAST:event_uncheckAllButtonActionPerformed
    
    /**
     * Clear the Shopping Cart
     * 
     * @param evt 
     */
    private void clearCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartButtonActionPerformed
        selectedItemsName.clear();
        cartList.setModel(selectedItemsName);
    }//GEN-LAST:event_clearCartButtonActionPerformed
    
    /**
     * Remove an item from the shopping cart.
     * 
     * @param evt 
     */
    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        int selectedItemIndex = cartList.getSelectedIndex();
        
        if (selectedItemIndex < 0) {
            JOptionPane.showMessageDialog(this, "No product selected");
            return;
        }
        
        selectedItemsName.remove(selectedItemIndex);
        cartList.setModel(selectedItemsName);
    }//GEN-LAST:event_removeItemButtonActionPerformed
    
    /**
     * Create and show a new checkout frame.
     * 
     * @param evt 
     */
    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        if (selectedItemsName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cart is empty.");
            return;
        }
        
        (new Checkout(this)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JCheckBox athlethicFeeItem;
    private javax.swing.JCheckBox burgerItem;
    private javax.swing.JList<String> cartList;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton clearCartButton;
    private javax.swing.JCheckBox examBookletItem;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox idLaceItem;
    private javax.swing.JCheckBox insuranceItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JCheckBox sefFormItem;
    private javax.swing.JCheckBox tshirtItem;
    private javax.swing.JButton uncheckAllButton;
    private javax.swing.JCheckBox unliRiceItem;
    // End of variables declaration//GEN-END:variables

}
